spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/android
    username: android
    password: android
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework: INFO
    ru.svanchukov.synthetic_human_core_starter.kafka.KafkaConsumer: INFO

audit:
  kafka-topic: audit-topic
  mode: KAFKA

kafka:
  bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true